apiVersion: apps/v1
kind: Deployment
metadata:
  name: companies-service
  labels:
    app: companies-service
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: companies-service
  template:
    metadata:
      labels:
        app: companies-service
    spec:
      containers:
        - name: companies-service
          image: tghcastro/gullveig-companies-service
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: companies-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: companies-service
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080