
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driverClassName: org.h2.Driver
    # For persisted DB
    url: jdbc:h2:file:~/data/testdb
    # For in memory DB (volatile)
    #url=jdbc:h2:mem:testdb
  h2:
    # H2 Console (http://localhost:8080/h2-console)
    console.enabled: true
