version: "3.7"

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - 8000:8000
      - 9000:9000
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/d/docker/volumes/test/portainer:/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 9001:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker