management:
  endpoints:
    web.exposure.include: "*"

spring:
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
  jackson:
    serialization.FAIL_ON_EMPTY_BEANS: false

server:
  port: 8070